Repository SEONGNAM-SELLDOK/damoim-api, pull requests merged in 2021-03, with the labels that each got.

#14 스터디 모임, 세미나
  build.gradle
  src/main/java/com/damoim/restapi/RestApiApplication.java
  src/main/java/com/damoim/restapi/boards/controller/BoardsController.java
  src/main/java/com/damoim/restapi/boards/dao/BoardsRepository.java
  src/main/java/com/damoim/restapi/boards/dao/BoardsRepositoryCustom.java
  src/main/java/com/damoim/restapi/boards/dao/BoardsRepositoryImpl.java
  src/main/java/com/damoim/restapi/boards/dao/BoardsSearchCondition.java
  src/main/java/com/damoim/restapi/boards/entity/Address.java
  src/main/java/com/damoim/restapi/boards/entity/BaseEntity.java
  src/main/java/com/damoim/restapi/boards/entity/BoardType.java
  src/main/java/com/damoim/restapi/boards/entity/Boards.java
  src/main/java/com/damoim/restapi/boards/entity/City.java
  src/main/java/com/damoim/restapi/boards/entity/Country.java
  src/main/java/com/damoim/restapi/boards/entity/DamoimTag.java
  src/main/java/com/damoim/restapi/boards/entity/Tag.java
  src/main/java/com/damoim/restapi/boards/model/ListBoardsResponse.java
  src/main/java/com/damoim/restapi/boards/model/ModifyBoardsRequest.java
  src/main/java/com/damoim/restapi/boards/model/ReadBoardsResponse.java
  src/main/java/com/damoim/restapi/boards/model/SaveBoardRequest.java
  src/main/java/com/damoim/restapi/boards/service/BoardsService.java
  src/main/java/com/damoim/restapi/config/FileProperties.java
  src/main/resources/application.yml
  src/main/resources/static/img/0000.jpg
  src/test/java/com/damoim/restapi/member/service/BoardsServiceTest.java
Labels: new feature

#15 [중고거래] (CRUD 최종 ) 마지막 코드리뷰 부탁드려요!
  .gitignore
  build.gradle
  src/main/java/com/damoim/restapi/config/DamoimFileUtil.java
  src/main/java/com/damoim/restapi/config/FileProperties.java
  src/main/java/com/damoim/restapi/secondhandtrade/config/MapperConfig.java
  src/main/java/com/damoim/restapi/secondhandtrade/config/SecurityConfiguration.java
  src/main/java/com/damoim/restapi/secondhandtrade/controller/UsedItemController.java
  src/main/java/com/damoim/restapi/secondhandtrade/dao/UsedItemRepository.java
  src/main/java/com/damoim/restapi/secondhandtrade/dao/UsedItemSearchRepository.java
  src/main/java/com/damoim/restapi/secondhandtrade/entity/useditem/Category.java
  src/main/java/com/damoim/restapi/secondhandtrade/entity/useditem/TradeType.java
  src/main/java/com/damoim/restapi/secondhandtrade/entity/useditem/UsedItem.java
  src/main/java/com/damoim/restapi/secondhandtrade/errormsg/ApiMessage.java
  src/main/java/com/damoim/restapi/secondhandtrade/errormsg/NotFoundPage.java
  src/main/java/com/damoim/restapi/secondhandtrade/mapper/EnumMapper.java
  src/main/java/com/damoim/restapi/secondhandtrade/mapper/EnumMapperType.java
  src/main/java/com/damoim/restapi/secondhandtrade/mapper/EnumValue.java
  src/main/java/com/damoim/restapi/secondhandtrade/model/ResponseModifyUsedItemClosed.java
  src/main/java/com/damoim/restapi/secondhandtrade/model/ResponseUsedItem.java
  src/main/java/com/damoim/restapi/secondhandtrade/model/SearchUsedItemRequest.java
  src/main/java/com/damoim/restapi/secondhandtrade/model/UsedItemRequest.java
  src/main/java/com/damoim/restapi/secondhandtrade/service/UsedItemService.java
  src/test/http/usedItem.http
  src/test/java/com/damoim/restapi/member/service/MemberServiceTest.java
  src/test/java/com/damoim/restapi/secondhandtrade/controller/UsedItemControllerTest.java
Labels: new feature

#23 #12 Recruit PR
  build.gradle
  src/main/java/com/damoim/restapi/recruit/controller/RecruitController.java
  src/main/java/com/damoim/restapi/recruit/dao/RecruitRepository.java
  src/main/java/com/damoim/restapi/recruit/dao/RecruitRepositorySupport.java
  src/main/java/com/damoim/restapi/recruit/dao/RecruitResponseMapper.java
  src/main/java/com/damoim/restapi/recruit/dao/RecruitSaveRequestMapper.java
  src/main/java/com/damoim/restapi/recruit/dao/RecruitUpdateRequestMapper.java
  src/main/java/com/damoim/restapi/recruit/entity/Recruit.java
  src/main/java/com/damoim/restapi/recruit/model/RecruitGetRequest.java
  src/main/java/com/damoim/restapi/recruit/model/RecruitResponse.java
  src/main/java/com/damoim/restapi/recruit/model/RecruitSaveRequest.java
  src/main/java/com/damoim/restapi/recruit/model/RecruitUpdateRequest.java
  src/main/java/com/damoim/restapi/recruit/service/RecruitService.java
  src/test/http/recruit.http
  src/test/java/com/damoim/restapi/recruit/service/RecruitServiceTest.java
Labels: new feature

#33 세미나, 스터디 정정사항 수정
  src/main/java/com/damoim/restapi/boards/controller/BoardController.java
  src/main/java/com/damoim/restapi/boards/controller/SeminarController.java
  src/main/java/com/damoim/restapi/boards/controller/StudyController.java
  src/main/java/com/damoim/restapi/boards/dao/BoardRepositoryCustom.java
  src/main/java/com/damoim/restapi/boards/dao/BoardRepositoryImpl.java
  src/main/java/com/damoim/restapi/boards/dao/BoardSearchCondition.java
  src/main/java/com/damoim/restapi/boards/entity/BaseEntity.java
  src/main/java/com/damoim/restapi/boards/model/ModifyBoardsRequest.java
  src/main/java/com/damoim/restapi/boards/model/ReadBoardsResponse.java
  src/main/java/com/damoim/restapi/boards/model/SaveBoardRequest.java
  src/main/java/com/damoim/restapi/boards/service/BoardService.java
  src/main/java/com/damoim/restapi/boards/service/BoardsService.java
  src/main/java/com/damoim/restapi/member/controller/MemberController.java
  src/main/java/com/damoim/restapi/member/dao/MemberMapper.java
  src/main/java/com/damoim/restapi/member/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/com/damoim/restapi/member/service/BoardServiceTest.java
Labels: bug, new feature

#31 파일업로드 보강
  src/main/java/com/damoim/restapi/boards/controller/SeminarController.java
  src/main/java/com/damoim/restapi/boards/controller/StudyController.java
  src/main/java/com/damoim/restapi/boards/dao/BoardRepositoryCustom.java
  src/main/java/com/damoim/restapi/boards/dao/BoardRepositoryImpl.java
  src/main/java/com/damoim/restapi/boards/dao/BoardSearchCondition.java
  src/main/java/com/damoim/restapi/boards/entity/BaseEntity.java
  src/main/java/com/damoim/restapi/boards/model/ModifyBoardsRequest.java
  src/main/java/com/damoim/restapi/boards/model/ReadBoardsResponse.java
  src/main/java/com/damoim/restapi/boards/model/SaveBoardRequest.java
  src/main/java/com/damoim/restapi/boards/service/BoardService.java
  src/main/java/com/damoim/restapi/config/DamoimFileUtil.java
  src/main/java/com/damoim/restapi/config/fileutil/DamoimFileUtil.java
  src/main/java/com/damoim/restapi/config/fileutil/ExceptionController.java
  src/main/java/com/damoim/restapi/config/fileutil/FileProperties.java
  src/main/java/com/damoim/restapi/config/fileutil/error/ErrorMessage.java
  src/main/java/com/damoim/restapi/config/fileutil/error/FileNotSaveException.java
  src/main/java/com/damoim/restapi/config/fileutil/error/NotSupportedTypeException.java
  src/main/java/com/damoim/restapi/config/fileutil/model/RequestFile.java
  src/main/java/com/damoim/restapi/config/web/WebConfig.java
  src/main/java/com/damoim/restapi/member/controller/MemberController.java
  src/main/java/com/damoim/restapi/member/dao/MemberMapper.java
  src/main/java/com/damoim/restapi/member/service/MemberService.java
  src/main/java/com/damoim/restapi/recruit/service/RecruitService.java
  src/main/java/com/damoim/restapi/secondhandtrade/controller/UsedItemController.java
  src/main/java/com/damoim/restapi/secondhandtrade/service/UsedItemService.java
  src/test/java/com/damoim/restapi/member/service/BoardServiceTest.java
Labels: new feature

#34 [fix] from 만 존재 , to만 존재하는 경우 조회조건 누락 추가.
  src/main/java/com/damoim/restapi/secondhandtrade/dao/UsedItemSearchRepository.java
Labels: bug

#36 [fix] RequestFile.class file 존재 여부 반환 메서드 추가.
  src/main/java/com/damoim/restapi/config/fileutil/model/RequestFile.java
  src/main/java/com/damoim/restapi/secondhandtrade/service/UsedItemService.java
Labels: bug

#18 oauth naver 추가
  build.gradle
  src/main/java/com/damoim/restapi/auth/AuthController.java
  src/main/java/com/damoim/restapi/auth/AuthProperties.java
  src/main/java/com/damoim/restapi/auth/AuthService.java
  src/main/java/com/damoim/restapi/auth/IndexController.java
  src/main/java/com/damoim/restapi/auth/JwtService.java
  src/main/java/com/damoim/restapi/auth/security/JwtAuthToken.java
  src/main/java/com/damoim/restapi/auth/security/JwtAuthenticationFiler.java
  src/main/java/com/damoim/restapi/auth/security/JwtAuthenticationProvider.java
  src/main/java/com/damoim/restapi/auth/security/NotYetJwtAuthToken.java
  src/main/java/com/damoim/restapi/auth/security/SecurityConfig.java
  src/main/java/com/damoim/restapi/config/RestTemplateConfig.java
  src/main/java/com/damoim/restapi/member/controller/MemberController.java
  src/main/java/com/damoim/restapi/member/dao/MemberRepository.java
  src/main/java/com/damoim/restapi/member/entity/Member.java
  src/main/java/com/damoim/restapi/member/model/GetMemberResponse.java
  src/main/java/com/damoim/restapi/member/model/TestUser.java
  src/main/java/com/damoim/restapi/member/service/MemberService.java
  src/main/java/com/damoim/restapi/secondhandtrade/config/SecurityConfiguration.java
  src/main/resources/application.yml
  src/main/resources/templates/index.html
  src/main/resources/templates/js/naveridlogin_js_sdk_2.0.2.js
  src/main/resources/templates/login.html
  src/test/java/com/damoim/restapi/secondhandtrade/controller/UsedItemControllerTest.java
Labels: new feature

#40 #17 lecture
  build.gradle
  src/main/java/com/damoim/restapi/config/jpa/EntityMapper.java
  src/main/java/com/damoim/restapi/lecture/controller/LectureController.java
  src/main/java/com/damoim/restapi/lecture/dao/LectureRepository.java
  src/main/java/com/damoim/restapi/lecture/dao/LectureRepositorySupport.java
  src/main/java/com/damoim/restapi/lecture/dao/LectureResponseMapper.java
  src/main/java/com/damoim/restapi/lecture/dao/LectureSaveRequestMapper.java
  src/main/java/com/damoim/restapi/lecture/dao/LectureUpdateRequestMapper.java
  src/main/java/com/damoim/restapi/lecture/entity/Lecture.java
  src/main/java/com/damoim/restapi/lecture/entity/LectureSubject.java
  src/main/java/com/damoim/restapi/lecture/model/LectureGetRequest.java
  src/main/java/com/damoim/restapi/lecture/model/LectureResponse.java
  src/main/java/com/damoim/restapi/lecture/model/LectureSaveRequest.java
  src/main/java/com/damoim/restapi/lecture/model/LectureUpdateRequest.java
  src/main/java/com/damoim/restapi/lecture/service/LectureService.java
  src/main/java/com/damoim/restapi/member/model/SaveMemberRequest.java
  src/test/http/lecture.http
  src/test/java/com/damoim/restapi/lecture/service/LectureServiceTest.java
Labels: new feature

#47 시큐리티 테스트를위한 커스텀애노테이션
  src/test/java/com/damoim/restapi/secondhandtrade/controller/WithAccount.java
  src/test/java/com/damoim/restapi/secondhandtrade/controller/WithAccountSecurityContextFactory.java
Labels: new feature

#44 #19 bookreview
  src/main/java/com/damoim/restapi/bookreview/controller/BookReviewController.java
  src/main/java/com/damoim/restapi/bookreview/dao/BookReviewRepository.java
  src/main/java/com/damoim/restapi/bookreview/dao/BookReviewRepositorySupporter.java
  src/main/java/com/damoim/restapi/bookreview/dao/BookReviewSaveRequestMapper.java
  src/main/java/com/damoim/restapi/bookreview/dao/BookReviewUpdateRequestMapper.java
  src/main/java/com/damoim/restapi/bookreview/entity/BookReview.java
  src/main/java/com/damoim/restapi/bookreview/model/BookReviewGetRequest.java
  src/main/java/com/damoim/restapi/bookreview/model/BookReviewSaveRequest.java
  src/main/java/com/damoim/restapi/bookreview/model/BookReviewUpdateRequest.java
  src/main/java/com/damoim/restapi/bookreview/service/BookReviewService.java
  src/test/http/bookreview.http
  src/test/java/com/damoim/restapi/bookreview/service/BookReviewServiceTest.java
Labels: new feature

#42 댓글 기능
  src/main/java/com/damoim/restapi/auth/security/SecurityConfig.java
  src/main/java/com/damoim/restapi/boards/entity/BoardType.java
  src/main/java/com/damoim/restapi/boards/service/BoardService.java
  src/main/java/com/damoim/restapi/config/errorhandler/ExceptionController.java
  src/main/java/com/damoim/restapi/config/errorhandler/message/ApiMessage.java
  src/main/java/com/damoim/restapi/config/errorhandler/message/TypeErrorMessage.java
  src/main/java/com/damoim/restapi/config/fileutil/ExceptionController.java
  src/main/java/com/damoim/restapi/reply/contoller/ReplyController.java
  src/main/java/com/damoim/restapi/reply/dao/ChildReplyRepository.java
  src/main/java/com/damoim/restapi/reply/dao/ReplyRepository.java
  src/main/java/com/damoim/restapi/reply/entity/ChildReply.java
  src/main/java/com/damoim/restapi/reply/entity/Reply.java
  src/main/java/com/damoim/restapi/reply/model/request/RequestDeleteReply.java
  src/main/java/com/damoim/restapi/reply/model/request/RequestEditReply.java
  src/main/java/com/damoim/restapi/reply/model/request/RequestSaveReply.java
  src/main/java/com/damoim/restapi/reply/model/response/ResponseEditReply.java
  src/main/java/com/damoim/restapi/reply/model/response/ResponseReply.java
  src/main/java/com/damoim/restapi/reply/model/response/ResponseUsedItemIncludeReply.java
  src/main/java/com/damoim/restapi/reply/service/BoardValidationService.java
  src/main/java/com/damoim/restapi/reply/service/ReplyClosedException.java
  src/main/java/com/damoim/restapi/reply/service/ReplyService.java
  src/main/java/com/damoim/restapi/secondhandtrade/controller/UsedItemController.java
  src/main/java/com/damoim/restapi/secondhandtrade/dao/UsedItemRepository.java
  src/main/java/com/damoim/restapi/secondhandtrade/dao/UsedItemSearchRepository.java
  src/main/java/com/damoim/restapi/secondhandtrade/entity/useditem/UsedItem.java
  src/main/java/com/damoim/restapi/secondhandtrade/errormsg/NotFoundResource.java
  src/main/java/com/damoim/restapi/secondhandtrade/model/useditem/ResponseModifyUsedItemClosed.java
  src/main/java/com/damoim/restapi/secondhandtrade/model/useditem/ResponseUsedItem.java
  src/main/java/com/damoim/restapi/secondhandtrade/model/useditem/SearchUsedItemRequest.java
  src/main/java/com/damoim/restapi/secondhandtrade/model/useditem/UsedItemRequest.java
  src/main/java/com/damoim/restapi/secondhandtrade/service/UsedItemService.java
  src/test/http/usedItem.http
  src/test/java/com/damoim/restapi/reply/service/ReplyServiceTest.java
  src/test/java/com/damoim/restapi/secondhandtrade/controller/UsedItemControllerTest.java
Labels: new feature

#48 Audit
  src/main/java/com/damoim/restapi/config/jpa/AuditorAwareImpl.java
  src/main/java/com/damoim/restapi/config/jpa/JpaAuditConfig.java
  src/main/java/com/damoim/restapi/secondhandtrade/controller/UsedItemController.java
  src/main/java/com/damoim/restapi/secondhandtrade/dao/UsedItemSearchRepository.java
  src/main/java/com/damoim/restapi/secondhandtrade/entity/useditem/UsedItem.java
  src/main/java/com/damoim/restapi/secondhandtrade/errormsg/NotFoundResource.java
  src/main/java/com/damoim/restapi/secondhandtrade/model/request/SearchUsedItemRequest.java
  src/main/java/com/damoim/restapi/secondhandtrade/model/request/UsedItemRequest.java
  src/main/java/com/damoim/restapi/secondhandtrade/model/response/ResponseModifyUsedItemClosed.java
  src/main/java/com/damoim/restapi/secondhandtrade/model/response/ResponseUsedItem.java
  src/main/java/com/damoim/restapi/secondhandtrade/model/useditem/UsedItemRequest.java
  src/main/java/com/damoim/restapi/secondhandtrade/service/UsedItemService.java
  src/main/resources/application.yml
  src/test/http/usedItem.http
  src/test/java/com/damoim/restapi/lecture/service/LectureServiceTest.java
  src/test/java/com/damoim/restapi/member/service/MemberServiceTest.java
  src/test/java/com/damoim/restapi/recruit/service/RecruitServiceTest.java
  src/test/java/com/damoim/restapi/reply/service/ReplyServiceTest.java
  src/test/java/com/damoim/restapi/secondhandtrade/controller/UsedItemControllerTest.java
Labels: new feature

#54 [BugFix] AuthUser casting error
  src/main/java/com/damoim/restapi/config/jpa/AuditorAwareImpl.java
Labels: bug

#52 Recruit, Lecture, BookReview 서비스 리턴 타입 각 Response 객체로 수정
  src/main/java/com/damoim/restapi/bookreview/controller/BookReviewController.java
  src/main/java/com/damoim/restapi/bookreview/dao/BookReviewResponseMapper.java
  src/main/java/com/damoim/restapi/bookreview/entity/BookReview.java
  src/main/java/com/damoim/restapi/bookreview/model/BookReviewResponse.java
  src/main/java/com/damoim/restapi/bookreview/model/BookReviewUpdateRequest.java
  src/main/java/com/damoim/restapi/bookreview/service/BookReviewService.java
  src/main/java/com/damoim/restapi/lecture/controller/LectureController.java
  src/main/java/com/damoim/restapi/lecture/entity/Lecture.java
  src/main/java/com/damoim/restapi/lecture/model/LectureSaveRequest.java
  src/main/java/com/damoim/restapi/lecture/model/LectureUpdateRequest.java
  src/main/java/com/damoim/restapi/lecture/service/LectureService.java
  src/main/java/com/damoim/restapi/recruit/controller/RecruitController.java
  src/main/java/com/damoim/restapi/recruit/entity/Recruit.java
  src/main/java/com/damoim/restapi/recruit/model/RecruitSaveRequest.java
  src/main/java/com/damoim/restapi/recruit/model/RecruitUpdateRequest.java
  src/main/java/com/damoim/restapi/recruit/service/RecruitService.java
  src/test/java/com/damoim/restapi/bookreview/service/BookReviewServiceTest.java
  src/test/java/com/damoim/restapi/lecture/service/LectureServiceTest.java
  src/test/java/com/damoim/restapi/recruit/service/RecruitServiceTest.java
  src/test/java/com/damoim/restapi/reply/service/ReplyServiceTest.java
Labels: enhancement

#56 #50 구인 댓글 기능 추가
  src/main/java/com/damoim/restapi/recruit/controller/RecruitController.java
  src/main/java/com/damoim/restapi/recruit/model/RecruitResponseWithReply.java
  src/main/java/com/damoim/restapi/recruit/model/RecruitSaveRequest.java
  src/main/java/com/damoim/restapi/recruit/service/RecruitService.java
  src/test/http/recruit.http
  src/test/java/com/damoim/restapi/recruit/service/RecruitServiceTest.java
Labels: new feature

#58 BookReview, Lecture 댓글 기능 추가
  src/main/java/com/damoim/restapi/boards/entity/BoardType.java
  src/main/java/com/damoim/restapi/bookreview/controller/BookReviewController.java
  src/main/java/com/damoim/restapi/bookreview/model/BookReviewResponseWithReply.java
  src/main/java/com/damoim/restapi/bookreview/service/BookReviewService.java
  src/main/java/com/damoim/restapi/lecture/controller/LectureController.java
  src/main/java/com/damoim/restapi/lecture/dao/LectureResponseWithReply.java
  src/main/java/com/damoim/restapi/lecture/model/LectureGetRequest.java
  src/main/java/com/damoim/restapi/lecture/service/LectureService.java
  src/main/java/com/damoim/restapi/reply/service/BoardValidationService.java
  src/test/http/bookreview.http
  src/test/http/lecture.http
  src/test/java/com/damoim/restapi/bookreview/service/BookReviewServiceTest.java
  src/test/java/com/damoim/restapi/lecture/service/LectureServiceTest.java
Labels: new feature

#59 Board count
  src/main/java/com/damoim/restapi/auth/security/SecurityConfig.java
  src/main/java/com/damoim/restapi/event/BoardClickedEvent.java
  src/main/java/com/damoim/restapi/event/BoardClickedListener.java
  src/main/java/com/damoim/restapi/event/boardcount/dao/BoardCountRepository.java
  src/main/java/com/damoim/restapi/event/boardcount/entity/BoardCount.java
  src/main/java/com/damoim/restapi/event/config/AsyncConfig.java
  src/main/java/com/damoim/restapi/secondhandtrade/service/UsedItemService.java
  src/test/http/usedItem.http
  src/test/java/com/damoim/restapi/event/BoardClickedListenerTest.java
Labels: new feature

#55 Toy board changelike
  src/main/java/com/damoim/restapi/boards/controller/SeminarController.java
  src/main/java/com/damoim/restapi/boards/controller/StudyController.java
  src/main/java/com/damoim/restapi/boards/dao/BoardRepository.java
  src/main/java/com/damoim/restapi/boards/dao/BoardRepositoryImpl.java
  src/main/java/com/damoim/restapi/boards/dao/BoardSearchCondition.java
  src/main/java/com/damoim/restapi/boards/entity/Board.java
  src/main/java/com/damoim/restapi/boards/model/ListBoardsIncludeLikeResponse.java
  src/main/java/com/damoim/restapi/boards/model/ListBoardsResponse.java
  src/main/java/com/damoim/restapi/boards/model/ModifyBoardsRequest.java
  src/main/java/com/damoim/restapi/boards/model/ReadBoardsIncludeLikeResponse.java
  src/main/java/com/damoim/restapi/boards/model/ReadBoardsResponse.java
  src/main/java/com/damoim/restapi/boards/model/SaveBoardRequest.java
  src/main/java/com/damoim/restapi/boards/service/BoardService.java
  src/main/java/com/damoim/restapi/community/controller/CommunityController.java
  src/main/java/com/damoim/restapi/community/dao/CommunityRepository.java
  src/main/java/com/damoim/restapi/community/dao/CommunityRepositoryCustom.java
  src/main/java/com/damoim/restapi/community/dao/CommunityRepositoryImpl.java
  src/main/java/com/damoim/restapi/community/dao/CommunitySearchCondition.java
  src/main/java/com/damoim/restapi/community/entity/Community.java
  src/main/java/com/damoim/restapi/community/model/ListCommunityResponse.java
  src/main/java/com/damoim/restapi/community/model/ModifyCommunityRequest.java
  src/main/java/com/damoim/restapi/community/model/ReadCommunityResponse.java
  src/main/java/com/damoim/restapi/community/model/SaveCommunityRequest.java
  src/main/java/com/damoim/restapi/community/service/CommunityService.java
  src/main/java/com/damoim/restapi/like/controller/BoardLikeController.java
  src/main/java/com/damoim/restapi/like/dao/BoardLikeRepository.java
  src/main/java/com/damoim/restapi/like/dao/BoardLikeRepositoryCustom.java
  src/main/java/com/damoim/restapi/like/dao/BoardLikeRepositoryImpl.java
  src/main/java/com/damoim/restapi/like/dao/BoardLikeSearchCondition.java
  src/main/java/com/damoim/restapi/like/dao/LikeStatusRepository.java
  src/main/java/com/damoim/restapi/like/entity/BoardLike.java
  src/main/java/com/damoim/restapi/like/entity/LikeStatus.java
  src/main/java/com/damoim/restapi/like/model/ChangeLikeRequest.java
  src/main/java/com/damoim/restapi/like/model/ListLikeResponse.java
  src/main/java/com/damoim/restapi/like/model/ReadLikeResponse.java
  src/main/java/com/damoim/restapi/like/model/SaveLikeRequest.java
  src/main/java/com/damoim/restapi/like/service/BoardLikeService.java
  src/main/java/com/damoim/restapi/member/dao/MemberRepository.java
  src/main/java/com/damoim/restapi/member/entity/Member.java
  src/main/java/com/damoim/restapi/member/service/MemberService.java
  src/test/java/com/damoim/restapi/like/service/LikeServiceTest.java
  src/test/java/com/damoim/restapi/member/service/BoardServiceTest.java
Labels: new feature

#63 [bugfix] Board Count Multi Thread 이슈
  src/main/java/com/damoim/restapi/event/BoardClickedEvent.java
  src/main/java/com/damoim/restapi/event/BoardClickedListener.java
  src/main/java/com/damoim/restapi/event/BoardCreatedEvent.java
  src/main/java/com/damoim/restapi/event/boardcount/entity/BoardCount.java
  src/main/java/com/damoim/restapi/secondhandtrade/service/UsedItemService.java
  src/test/java/com/damoim/restapi/event/BoardClickedListenerTest.java
  src/test/java/com/damoim/restapi/reply/service/ReplyServiceTest.java
Labels: bug

#64 도서리뷰, 강의, 구인 리턴 타입 수정
  src/main/java/com/damoim/restapi/bookreview/controller/BookReviewController.java
  src/main/java/com/damoim/restapi/bookreview/model/BookReviewItemResponse.java
  src/main/java/com/damoim/restapi/bookreview/model/BookReviewItemWithReplyResponse.java
  src/main/java/com/damoim/restapi/lecture/controller/LectureController.java
  src/main/java/com/damoim/restapi/lecture/model/LectureItemResponse.java
  src/main/java/com/damoim/restapi/lecture/model/LectureItemWithReplyResponse.java
  src/main/java/com/damoim/restapi/recruit/controller/RecruitController.java
  src/main/java/com/damoim/restapi/recruit/model/RecruitItemResponse.java
  src/main/java/com/damoim/restapi/recruit/model/RecruitItemWithReplyResponse.java
  src/test/http/recruit.http
Labels: enhancement
